#!/bin/bash

# 执行命令
# 例如：./hdc-aarch64-apple-darwin arg1 -a --arg2 any-string-that-matches-the-validator

# 获取参数
arg1=$1
arg2=$2
arg3=$3
arg4=$4


echo "参数1: $arg1"
echo "参数2: $arg2"
echo "参数3: $arg3"
echo "参数4: $arg4"

